CREATE DATABASE pubs;

USE pubs;

CREATE TABLE pub (
COD_PUB VARCHAR (20) NOT NULL,
NOMBRE VARCHAR (20) NOT NULL,
LICENCIA_FISCAL VARCHAR (20) NOT NULL,
DOMICILIO VARCHAR (20),
FECHA_APERTURA DATE NOT NULL,
HORARIO ENUM('HOR1','HOR2','HOR3') NOT NULL,
COD_LOCALIDAD INT (10) NOT NULL,
PRIMARY KEY (COD_PUB)
);

CREATE TABLE titular (
DNI_TITULAR VARCHAR (9) NOT NULL,
NOMBRE VARCHAR (20) NOT NULL,
DOMICILIO VARCHAR (20),
COD_PUB VARCHAR(10) NOT NULL,
PRIMARY KEY (DNI_TITULAR)
);

CREATE TABLE empleado (
DNI_EMPLEADO VARCHAR (9) NOT NULL,
NOMBRE VARCHAR (20) NOT NULL,
DOMICILIO VARCHAR (20),
PRIMARY KEY (DNI_EMPLEADO)
);

CREATE TABLE existencias (
COD_ARTICULO VARCHAR(20) NOT NULL,
NOMBRE VARCHAR (20) NOT NULL,
CANTIDAD DECIMAL (10,2) NOT NULL,
PRECIO DECIMAL (10,2) NOT NULL,
COD_PUB VARCHAR (20) NOT NULL,
CHECK (PRECIO <> 0)
);

CREATE TABLE localidad (
COD_LOCALIDAD INT(10) NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR (20) NOT NULL,
PRIMARY KEY (COD_LOCALIDAD)
);

CREATE TABLE pub_empleado (
COD_PUB VARCHAR(20) NOT NULL,
DNI_EMPLEADO VARCHAR(9) NOT NULL,
FUNCION ENUM('CAMARERO', 'SEGURIDAD', 'LIMPIEZA') NOT NULL,
PRIMARY KEY (COD_PUB)
);

ALTER TABLE pub
ADD CONSTRAINT fk_localidad FOREIGN KEY (COD_LOCALIDAD) REFERENCES localidad(COD_LOCALIDAD);

ALTER TABLE titular
ADD CONSTRAINT fk_pub FOREIGN KEY (COD_PUB) REFERENCES pub(COD_PUB);

ALTER TABLE existencias
ADD CONSTRAINT fk_pub_existencias FOREIGN KEY (COD_PUB) REFERENCES pub(COD_PUB);

ALTER TABLE pub_empleado
ADD CONSTRAINT fk_dni_empleado FOREIGN KEY (DNI_EMPLEADO) REFERENCES empleado(DNI_EMPLEADO);




